# Gliders Final Project LOOK THROUGH

### Karen's Code

In [3]:
import numpy                 as np
import pandas                as pd
import matplotlib.pyplot     as plt
import seaborn               as sns
import sklearn.metrics       as Metrics

import folium  #needed for interactive map
from folium.plugins import HeatMap
from matplotlib.patches import Patch

from   collections           import Counter
from   sklearn               import preprocessing
from   datetime              import datetime
from   collections           import Counter
from   math                  import exp
from   sklearn.linear_model  import LinearRegression as LinReg
from   sklearn.metrics       import mean_absolute_error
from   sklearn.metrics       import median_absolute_error
from   sklearn.metrics       import r2_score
import statsmodels
import statsmodels.api as sm
from statsmodels.formula.api import ols
import scipy 
import statsmodels.formula.api as smf


%matplotlib inline
sns.set()

In [4]:
df_bottle = pd.read_excel('Bottle data/Bottle Oxygen Data.xlsx')
df_bottle.head()

,Station_ID,Year_UTC,Month_UTC,Day_UTC,Hour_UTC,Minute_UTC,Latitude,Longitude,Cast_number,Sample_ID,...,CTDTEMP,CTDTEMP_FLAG,CTDSAL,CTDSAL_FLAG,CTDOXY,CTDOXY_FLAG,Oxygen,Oxygen_FLAG,best_Oxygen,best_Oxygen_FLAG
0,1,2021,10,22,21,7,49.101389,-67.2775,TRXD001,D-001132,...,6.2055,2,34.5830,2,36.702147,2,28.908497,2,28.908497,2
1,1,2021,10,22,21,7,49.101389,-67.2775,TRXD001,D-001133,...,5.4780,2,34.2430,2,57.633972,2,-999.000000,9,57.633972,2
2,1,2021,10,22,21,7,49.101389,-67.2775,TRXD001,D-001134,...,4.4462,2,33.7871,2,100.409764,2,90.840147,2,90.840147,2
3,1,2021,10,22,21,7,49.101389,-67.2775,TRXD001,D-001135,...,1.6449,2,32.3563,2,253.560071,2,244.645609,2,244.645609,2
4,1,2021,10,22,21,7,49.101389,-67.2775,TRXD001,D-001136,...,10.2512,2,30.3845,2,265.664677,2,-999.000000,9,265.664677,2

In [5]:
df_bottle2 = df_bottle[(df_bottle['CTDTEMP_FLAG'] == 2) & (df_bottle['CTDPRES_FLAG'] == 2)& (df_bottle['CTDSAL_FLAG'] == 2)&(df_bottle['CTDOXY_FLAG'] == 2)&(df_bottle['Oxygen_FLAG'] == 2) & (df_bottle['best_Oxygen_FLAG'] == 2) ]

In [6]:
df_bottle2.head()

,Station_ID,Year_UTC,Month_UTC,Day_UTC,Hour_UTC,Minute_UTC,Latitude,Longitude,Cast_number,Sample_ID,...,CTDTEMP,CTDTEMP_FLAG,CTDSAL,CTDSAL_FLAG,CTDOXY,CTDOXY_FLAG,Oxygen,Oxygen_FLAG,best_Oxygen,best_Oxygen_FLAG
0,1,2021,10,22,21,7,49.101389,-67.277500,TRXD001,D-001132,...,6.2055,2,34.5830,2,36.702147,2,28.908497,2,28.908497,2
2,1,2021,10,22,21,7,49.101389,-67.277500,TRXD001,D-001134,...,4.4462,2,33.7871,2,100.409764,2,90.840147,2,90.840147,2
3,1,2021,10,22,21,7,49.101389,-67.277500,TRXD001,D-001135,...,1.6449,2,32.3563,2,253.560071,2,244.645609,2,244.645609,2
5,1,2021,10,22,21,7,49.101389,-67.277500,TRXD001,D-001137,...,10.6053,2,30.0266,2,269.595853,2,269.623002,2,269.623002,2
6,2,2021,10,23,2,10,49.428889,-66.331944,TRXD002,D-001138,...,6.5414,2,34.7783,2,45.814081,2,37.712004,2,37.712004,2

In [7]:
df_bottle2.shape

(38, 22)

In [8]:
df_bottle3 = df_bottle[df_bottle['best_Oxygen_FLAG']==2]
df_bottle3.head()

,Station_ID,Year_UTC,Month_UTC,Day_UTC,Hour_UTC,Minute_UTC,Latitude,Longitude,Cast_number,Sample_ID,...,CTDTEMP,CTDTEMP_FLAG,CTDSAL,CTDSAL_FLAG,CTDOXY,CTDOXY_FLAG,Oxygen,Oxygen_FLAG,best_Oxygen,best_Oxygen_FLAG
0,1,2021,10,22,21,7,49.101389,-67.2775,TRXD001,D-001132,...,6.2055,2,34.5830,2,36.702147,2,28.908497,2,28.908497,2
1,1,2021,10,22,21,7,49.101389,-67.2775,TRXD001,D-001133,...,5.4780,2,34.2430,2,57.633972,2,-999.000000,9,57.633972,2
2,1,2021,10,22,21,7,49.101389,-67.2775,TRXD001,D-001134,...,4.4462,2,33.7871,2,100.409764,2,90.840147,2,90.840147,2
3,1,2021,10,22,21,7,49.101389,-67.2775,TRXD001,D-001135,...,1.6449,2,32.3563,2,253.560071,2,244.645609,2,244.645609,2
4,1,2021,10,22,21,7,49.101389,-67.2775,TRXD001,D-001136,...,10.2512,2,30.3845,2,265.664677,2,-999.000000,9,265.664677,2

In [9]:
df_bottle3['best_Oxygen'].describe()

count    503.000000
mean     180.518979
std      102.189444
min       28.908497
25%       88.914410
50%      128.209624
75%      289.439961
max      363.904648
Name: best_Oxygen, dtype: float64

In [10]:
df_cabot1= pd.read_csv('Glider data/cabot_20200717_114_delayed_corrected_v4.csv')
df_cabot1.head()

,time,latitude,longitude,depth,sea_water_temperature,sea_water_practical_salinity,sea_water_density,micromoles_of_oxygen_per_unit_mass_in_sea_water
0,2020-07-17 18:52:10,47.417050,-63.907473,23.203598,3.0303,30.195456,1024.161834,290.021550
1,2020-07-17 18:52:12,47.417050,-63.907469,23.332499,2.9849,30.200268,1024.169918,290.953106
2,2020-07-17 18:52:14,47.417049,-63.907464,23.659710,2.9294,30.209164,1024.182979,292.816304
3,2020-07-17 18:52:16,47.417049,-63.907460,23.838190,2.8807,30.208725,1024.187318,291.882880
4,2020-07-17 18:52:18,47.417049,-63.907456,24.105907,2.8215,30.220029,1024.202236,293.740371

In [50]:
df_cabot1.shape

(1014147, 8)

In [48]:
df_cabot11 = df_cabot1[(df_cabot1['latitude'] < 48.5) & (df_cabot1['longitude'] < -63)]
df_cabot11.shape

(1014147, 8)

In [11]:
df_cabot2 = pd.read_csv('Glider data/cabot_20210706_135_delayed_corrected_v4.csv')
df_cabot2.head()

,time,latitude,longitude,depth,sea_water_temperature,sea_water_practical_salinity,sea_water_density,micromoles_of_oxygen_per_unit_mass_in_sea_water
0,2021-07-06 18:12:00,48.156968,-61.190255,66.019683,0.95210,32.133159,1026.063329,298.319833
1,2021-07-06 18:12:02,48.156970,-61.190256,66.153507,0.95210,32.136732,1026.066843,298.130489
2,2021-07-06 18:12:04,48.156971,-61.190257,66.426109,0.95315,32.142983,1026.073111,298.120317
3,2021-07-06 18:12:06,48.156973,-61.190257,66.693750,0.95485,32.148754,1026.078931,298.065631
4,2021-07-06 18:12:08,48.156975,-61.190258,66.956436,0.95265,32.156643,1026.086663,297.994816

In [52]:
df_cabot22 = df_cabot2[(df_cabot2['latitude'] < 48.5) & (df_cabot2['longitude'] < -63)]
df_cabot22.shape

(0, 8)

In [12]:
df_cabot3 = pd.read_csv('Glider data/cabot_20220603_155_delayed_corrected_v4.csv')
df_cabot3.head()

,time,latitude,longitude,depth,sea_water_temperature,sea_water_practical_salinity,sea_water_density,micromoles_of_oxygen_per_unit_mass_in_sea_water
0,2022-06-03 16:30:21,47.659720,-64.147956,0.079331,8.3528,29.668861,1023.044151,275.935655
1,2022-06-03 16:30:23,47.659723,-64.147958,-0.019833,8.3539,29.667250,1023.042274,275.938425
2,2022-06-03 16:30:25,47.659727,-64.147960,-0.009916,8.3575,29.668277,1023.042616,275.936138
3,2022-06-03 16:30:27,47.659731,-64.147961,0.009916,8.3640,29.668525,1023.041983,275.935375
4,2022-06-03 16:30:29,47.659735,-64.147962,0.049582,8.3640,29.666423,1023.040521,275.939873

In [56]:
df_cabot3.shape

(349146, 8)

In [54]:
df_cabot33 = df_cabot3[(df_cabot3['latitude'] < 48.5) & (df_cabot3['longitude'] < -63)]
df_cabot33.shape

(349146, 8)

In [13]:
df_cabot4 = pd.read_csv('Glider data/cabot_20220727_158_delayed_corrected_v4.csv')
df_cabot4.head()

,time,latitude,longitude,depth,sea_water_temperature,sea_water_practical_salinity,sea_water_density,micromoles_of_oxygen_per_unit_mass_in_sea_water
0,2022-07-27 19:41:32,47.642197,-64.148685,-0.039666,18.075899,26.125972,1018.477832,237.271290
1,2022-07-27 19:41:34,47.642196,-64.148692,0.039666,18.075500,26.125956,1018.478268,237.271249
2,2022-07-27 19:41:36,47.642195,-64.148699,0.079331,18.077700,26.125776,1018.477797,237.271711
3,2022-07-27 19:41:39,47.642192,-64.148711,0.049582,18.065599,26.127014,1018.481421,237.270023
4,2022-07-27 19:41:41,47.642188,-64.148720,0.109081,18.072800,26.127654,1018.480502,237.269099

In [60]:
df_cabot4.shape

(760518, 8)

In [58]:
df_cabot44 = df_cabot4[(df_cabot4['latitude'] < 48.5) & (df_cabot4['longitude'] < -63)]
df_cabot44.shape

(760518, 8)

In [14]:
df_fundy1 = pd.read_csv('Glider data/fundy_20190604_99_delayed_corrected_v4.csv')
df_fundy1.head()

,time,latitude,longitude,depth,sea_water_temperature,sea_water_practical_salinity,sea_water_density,micromoles_of_oxygen_per_unit_mass_in_sea_water
0,2019-06-04 17:11:16,47.949421,-64.030443,0.198323,8.32360,27.117153,1021.050592,350.597474
1,2019-06-04 17:11:26,47.949445,-64.030491,0.198323,8.32360,27.117153,1021.050592,350.597474
2,2019-06-04 17:11:36,47.949455,-64.030514,0.198323,8.32360,27.117153,1021.050592,350.597474
3,2019-06-04 17:11:46,47.949465,-64.030545,0.223113,8.25655,27.102073,1021.047914,351.595241
4,2019-06-04 17:22:08,47.949251,-64.030358,64.692607,0.16640,31.863393,1025.882862,300.680069

In [64]:
df_fundy1.shape

(45636, 8)

In [62]:
df_fundy11 = df_fundy1[(df_fundy1['latitude'] < 48.5) & (df_fundy1['longitude'] < -63)]
df_fundy11.shape

(45636, 8)

In [15]:
df_fundy2 = pd.read_csv('Glider data/fundy_20230726_175_delayed_corrected_v4.csv')
df_fundy2.head()

,time,latitude,longitude,depth,sea_water_temperature,sea_water_practical_salinity,sea_water_density,micromoles_of_oxygen_per_unit_mass_in_sea_water
0,2023-07-26 16:20:00,49.062991,-64.140656,0.248870,19.576300,27.116364,1018.873043,225.296803
1,2023-07-26 16:20:02,49.062991,-64.140653,0.248870,19.576300,27.116364,1018.873043,225.489740
2,2023-07-26 16:20:04,49.062992,-64.140650,0.248870,19.576300,27.116364,1018.873043,225.582894
3,2023-07-26 16:20:06,49.062992,-64.140647,0.256405,19.564700,27.127606,1018.884502,225.593848
4,2023-07-26 16:20:08,49.062993,-64.140638,0.261710,19.545151,27.145109,1018.902681,225.525192

In [66]:
df_fundy22 = df_fundy2[(df_fundy2['latitude'] < 48.5) & (df_fundy2['longitude'] < -63)]
df_fundy22.shape

(0, 8)

In [16]:
df_peggy1 = pd.read_csv('Glider data/peggy_20220421_151_delayed_corrected_v4.csv')
df_peggy1.head()

,time,latitude,longitude,depth,sea_water_temperature,sea_water_practical_salinity,sea_water_density,micromoles_of_oxygen_per_unit_mass_in_sea_water
0,2022-04-21 22:54:34,47.402161,-60.243679,0.359776,0.3615,31.177989,1025.010359,367.417206
1,2022-04-21 22:54:36,47.402163,-60.243682,0.359776,0.3615,31.177989,1025.010359,367.417206
2,2022-04-21 22:54:38,47.402164,-60.243685,0.359776,0.3615,31.177989,1025.010359,367.417206
3,2022-04-21 22:54:40,47.402165,-60.243687,0.322886,0.3634,31.178549,1025.010541,367.415130
4,2022-04-21 22:54:42,47.402164,-60.243694,0.302656,0.3634,31.178300,1025.010243,367.415627

In [68]:
df_peggy11 = df_peggy1[(df_peggy1['latitude'] < 48.5) & (df_peggy1['longitude'] < -63)]
df_peggy11.shape

(0, 8)

In [70]:
df_peggy2 = pd.read_csv('Glider data/peggy_20230417_167_delayed_corrected_v4.csv')
df_peggy2.head()

,time,latitude,longitude,depth,sea_water_temperature,sea_water_practical_salinity,sea_water_density,micromoles_of_oxygen_per_unit_mass_in_sea_water
0,2023-04-17 17:40:01,48.072448,-60.956985,21.617000,0.7693,31.616191,1025.444472,356.639511
1,2023-04-17 17:40:03,48.072449,-60.956991,22.009336,0.8136,31.591333,1025.423930,356.437646
2,2023-04-17 17:40:05,48.072449,-60.956996,22.411882,0.8389,31.595985,1025.428196,356.151348
3,2023-04-17 17:40:07,48.072449,-60.957002,22.806001,0.8654,31.594663,1025.427544,355.824027
4,2023-04-17 17:40:09,48.072450,-60.957007,23.205968,0.8694,31.584602,1025.421163,355.504200

In [72]:
df_peggy22 = df_peggy2[(df_peggy2['latitude'] < 48.5) & (df_peggy2['longitude'] < -63)]
df_peggy22.shape

(0, 8)

In [18]:
df_sambro = pd.read_csv('Glider data/sambro_20210705_134_delayed_corrected_v4.csv')
df_sambro.head()

,time,latitude,longitude,depth,sea_water_temperature,sea_water_practical_salinity,sea_water_density,micromoles_of_oxygen_per_unit_mass_in_sea_water
0,2021-07-05 21:21:25,47.413912,-63.435190,0.220447,14.5823,28.613520,1021.147121,237.217550
1,2021-07-05 21:21:27,47.413905,-63.435205,0.225901,14.5879,28.616909,1021.148613,237.211893
2,2021-07-05 21:21:29,47.413902,-63.435215,0.220347,14.5904,28.616147,1021.147492,237.213046
3,2021-07-05 21:21:31,47.413904,-63.435218,0.172450,14.5918,28.614420,1021.145661,237.215527
4,2021-07-05 21:21:33,47.413911,-63.435213,0.213208,14.5903,28.614970,1021.146575,237.214930

In [76]:
df_sambro.shape

(378473, 8)

In [74]:
df_sambro1 = df_sambro[(df_sambro['latitude'] < 48.5) & (df_sambro['longitude'] < -63)]
df_sambro1.shape

(378473, 8)

In [19]:
df_scotia1 = pd.read_csv('Glider data/scotia_20180720_87_delayed_corrected_v4.csv')
df_scotia1.head()

,time,latitude,longitude,depth,sea_water_temperature,sea_water_practical_salinity,sea_water_density,micromoles_of_oxygen_per_unit_mass_in_sea_water
0,2018-07-20 01:02:01,47.740488,-64.044847,0.228076,15.9484,27.106531,1019.704115,260.528649
1,2018-07-20 01:02:03,47.740486,-64.044844,0.347071,15.9479,27.110453,1019.707765,260.458040
2,2018-07-20 01:02:05,47.740485,-64.044841,0.198327,15.9478,27.110223,1019.706941,260.469886
3,2018-07-20 01:02:08,47.740482,-64.044837,0.307406,15.9478,27.110103,1019.707340,260.483404
4,2018-07-20 01:02:10,47.740481,-64.044834,0.267741,15.9474,27.110303,1019.707400,260.424064

In [80]:
df_scotia1.shape

(321616, 8)

In [78]:
df_scotia11 = df_scotia1[(df_scotia1['latitude'] < 48.5) & (df_scotia1['longitude'] < -63)]
df_scotia11.shape

(321616, 8)

In [20]:
df_scotia2 = pd.read_csv('Glider data/scotia_20181113_95_delayed_corrected_v4.csv')
df_scotia2.head()

,time,latitude,longitude,depth,sea_water_temperature,sea_water_practical_salinity,sea_water_density,micromoles_of_oxygen_per_unit_mass_in_sea_water
0,2018-11-13 14:28:33,47.660530,-64.408352,0.396656,4.4046,29.618965,1023.474686,289.033152
1,2018-11-13 14:28:35,47.660529,-64.408351,0.337158,4.4045,29.623238,1023.477804,288.951502
2,2018-11-13 14:28:37,47.660529,-64.408350,0.356990,4.4039,29.612000,1023.469040,288.994825
3,2018-11-13 14:28:39,47.660529,-64.408349,0.446238,4.4033,29.624264,1023.479248,288.865910
4,2018-11-13 14:28:41,47.660528,-64.408348,0.426405,4.4026,29.617865,1023.474145,288.982826

In [84]:
df_scotia2.shape

(368411, 8)

In [82]:
df_scotia22 = df_scotia2[(df_scotia2['latitude'] < 48.5) & (df_scotia2['longitude'] < -63)]
df_scotia22.shape

(368411, 8)

In [21]:
df_scotia3 = pd.read_csv('Glider data/scotia_20190605_100_delayed_corrected_v4.csv')
df_scotia3.head()

,time,latitude,longitude,depth,sea_water_temperature,sea_water_practical_salinity,sea_water_density,micromoles_of_oxygen_per_unit_mass_in_sea_water
0,2019-06-05 15:35:00,47.532469,-64.235658,0.178497,9.2579,28.173026,1021.743999,282.224517
1,2019-06-05 15:35:02,47.532470,-64.235652,0.148748,9.2580,28.172655,1021.743558,282.161335
2,2019-06-05 15:35:04,47.532473,-64.235646,0.133873,9.2587,28.172211,1021.743038,282.153518
3,2019-06-05 15:35:06,47.532476,-64.235640,0.203289,9.2592,28.172144,1021.743234,282.352917
4,2019-06-05 15:35:08,47.532477,-64.235634,0.257829,9.2589,28.172562,1021.743856,282.240300

In [88]:
df_scotia3.shape

(797256, 8)

In [86]:
df_scotia33 = df_scotia3[(df_scotia3['latitude'] < 48.5) & (df_scotia3['longitude'] < -63)]
df_scotia33.shape

(797256, 8)

In [22]:
df_scotia4 = pd.read_csv('Glider data/scotia_20210719_136_delayed_corrected_v4.csv')
df_scotia4.head()

,time,latitude,longitude,depth,sea_water_temperature,sea_water_practical_salinity,sea_water_density,micromoles_of_oxygen_per_unit_mass_in_sea_water
0,2021-07-19 21:28:07,47.029421,-60.713808,0.125351,17.603201,29.199342,1020.935021,227.308429
1,2021-07-19 21:28:09,47.029422,-60.713807,0.125351,17.603201,29.199342,1020.935021,227.308429
2,2021-07-19 21:28:11,47.029424,-60.713800,0.125351,17.603201,29.199342,1020.935021,227.308429
3,2021-07-19 21:28:13,47.029425,-60.713793,0.136557,17.595501,29.203521,1020.940062,227.302130
4,2021-07-19 21:28:15,47.029423,-60.713786,0.162143,17.589701,29.206499,1020.943806,227.297754

In [90]:
df_scotia44 = df_scotia4[(df_scotia4['latitude'] < 48.5) & (df_scotia4['longitude'] < -63)]
df_scotia44.shape

(0, 8)

In [23]:
df_scotia5 = pd.read_csv('Glider data/scotia_20220421_150_delayed_corrected_v4.csv')
df_scotia5.head()

,time,latitude,longitude,depth,sea_water_temperature,sea_water_practical_salinity,sea_water_density,micromoles_of_oxygen_per_unit_mass_in_sea_water
0,2022-04-21 19:48:20,47.398535,-60.236032,0.340835,0.6758,31.214809,1025.024228,332.216854
1,2022-04-21 19:48:22,47.398533,-60.236033,0.340835,0.6758,31.214809,1025.024228,333.132052
2,2022-04-21 19:48:24,47.398531,-60.236033,0.340835,0.6758,31.214809,1025.024228,332.216854
3,2022-04-21 19:48:26,47.398530,-60.236032,0.319514,0.6775,31.215291,1025.024424,332.215338
4,2022-04-21 19:48:28,47.398529,-60.236031,0.334092,0.6775,31.213485,1025.023041,332.220074

In [92]:
df_scotia55 = df_scotia5[(df_scotia5['latitude'] < 48.5) & (df_scotia5['longitude'] < -63)]
df_scotia55.shape

(0, 8)

In [24]:
df_shad = pd.read_csv('Glider data/shad_20230601_168_delayed_corrected_v4.csv')
df_shad.head()

,time,latitude,longitude,depth,sea_water_temperature,sea_water_practical_salinity,sea_water_density,micromoles_of_oxygen_per_unit_mass_in_sea_water
0,2023-06-01 14:29:20,47.678335,-64.166840,0.182858,10.0361,26.974412,1020.69212,284.668192
1,2023-06-01 14:29:32,47.678412,-64.166565,0.182858,10.0361,26.974412,1020.69212,284.668192
2,2023-06-01 14:29:34,47.678428,-64.166510,0.182858,10.0361,26.974412,1020.69212,284.668192
3,2023-06-01 14:29:36,47.678443,-64.166455,0.182858,10.0361,26.974412,1020.69212,284.668192
4,2023-06-01 14:29:38,47.678459,-64.166400,0.182858,10.0361,26.974412,1020.69212,284.668192

In [96]:
df_shad.shape

(495131, 8)

In [94]:
df_shad1 = df_shad[(df_shad['latitude'] < 48.5) & (df_shad['longitude'] < -63)]
df_shad1.shape

(495131, 8)